name: Windows-MSVC-Reference

on: push

jobs:
  windows_ref:
    name: msvc
    runs-on: [windows-latest]
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

